routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

\Illuminate\Support\Facades\Route::middleware(['auth'])->prefix('admin')->namespace('Backend')->name('admin.')->group(function () {
    \Illuminate\Support\Facades\Route::get('/', 'DashboardController@index')->name('index');

    \Illuminate\Support\Facades\Route::get('/setting', 'SettingController@index')->name('setting.index');
    \Illuminate\Support\Facades\Route::post('/setting/store', 'SettingController@store')->name('setting.store');

    \Illuminate\Support\Facades\Route::get('/debug', 'DebugController@index')->name('setting.debug');

    \Illuminate\Support\Facades\Route::post('/setting/setwebhook', 'SettingController@setwebhook')->name('setting.setwebhook');
    \Illuminate\Support\Facades\Route::post('/setting/getwebhookinfo', 'SettingController@getwebhookinfo')->name('setting.getwebhookinfo');
});

Route::post(Telegram\Bot\Laravel\Facades\Telegram::getAccessToken(), function () {
    app('App\Http\Controllers\Backend\TelegramController')->webhook();
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{
    public function index () {
        return view('backend.index');
    }
}

app/Http/Controllers/Backend/DebugController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DebugController extends Controller
{
    public function index (){

        dd(file_get_contents('webHook_first.log',FILE_APPEND));
    }
}

app/Http/Controllers/Backend/SettingController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Setting;
use Illuminate\Http\Request;
use Telegram\Bot\Laravel\Facades\Telegram;


class SettingController extends Controller
{
    public function index()
    {
        return view('backend.setting', Setting::getSettings());

    }

    public function store(Request $request)
    {
        Setting::where('key', '!=', null)->delete();

        foreach ($request->except('_token') as $key => $value) {

            $setting        = new Setting;
            $setting->key   = $key;
            $setting->value = $request->$key;
            $setting->save();

        }
        return redirect()->route('admin.setting.index');
    }

    public function setwebhook(Request $request)
    {
 //lol
        $result = $this->sendTelegramData('setwebhook', [
                'query' => ['url' => $request->url . '/' . Telegram::getAccessToken()]
        ]);
        return redirect()->route('admin.setting.index')->with('status', $result);
    }

    public function getwebhookinfo(Request $request)
    {
        $result = $this->sendTelegramData('getWebhookInfo');
        file_put_contents('webHook_first.log','------'.$result."------\n\n",FILE_APPEND);
        return redirect()->route('admin.setting.index')->with('status', $result);
    }

    public function sendTelegramData($route = '', $params = [], $method = 'POST')
    {

        $client = new \GuzzleHttp\Client(['base_uri' => 'https://api.telegram.org/bot'. Telegram::getAccessToken().'/']);

        $result = $client->request($method, $route, $params);

        return (string)$result->getBody();
    }


}

app/Http/Controllers/Backend/TelegramController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\TelegramUser;
use Telegram;
use Telegram\Bot\Actions;
use Telegram\Bot\Api;

class TelegramController extends Controller
{
    /**
     * @throws Telegram\Bot\Exceptions\TelegramSDKException
     */

    protected $telegram_webhook;

    public function __construct()
    {

        $this->telegram_webhook = Telegram::getWebhookUpdates();
    }

    public function webhook()
    {

        $telegram = $this->telegram_webhook;

        if (isset($telegram['callback_query'])) {
            if (!TelegramUser::find($telegram['callback_query']['from']['id'])) {
                TelegramUser::create($telegram['callback_query']['from']);
            }
        } else {
            if (!TelegramUser::find($telegram['message']['from']['id'])) {
                TelegramUser::create($telegram['message']['from']);
            }
        }


        $this->checkCommand();
        sleep(1);
        $this->switchCommand();

        Telegram::commandsHandler(true);


    }

    /**
     *
     */
    public function switchCommand()
    {
        $telegram = $this->telegram_webhook;
        $command  = $this->getLastCommand();
        file_put_contents('webHook_first.log', '--Swtch----'.$command."------\n\n", FILE_APPEND);

        if (isset($telegram['callback_query'])) {
            if ($telegram['callback_query']['data'] == $command) {
                if ($command == 'SetData' || $command == 'Указать' || $command == 'ResetData') {

                    $this->setDataCommand();
                } elseif ($command == '/start') {
                    $this->startCommand();
                }
            }
        } else {
            if ($telegram['message']['text'] == $command) {
                {

                }
            } else {
//                \Telegram::sendMessage([
//                    'chat_id' => $telegram['message']['chat']['id'],
//                    'text'    => 'Вы ввели не сущетсвующую команду2',
//                ]);
                if ($command == 'SetData' || $command == 'Указать' || $command == 'ResetData') {
                    $this->setDataCommand();
                }
            }


        };
//            if ($telegram['message']['text'] == $command) {
//                if ($command == 'SetData') {
//                    \Telegram::sendMessage([
//                        'chat_id' => $telegram['message']['chat']['id'],
//                        'text'    => 'Ранее была выбрана команда Указать данные',
//                    ]);
//                } elseif ($command == '/start') {
//                    \Telegram::sendMessage([
//                        'chat_id' => $telegram['message']['chat']['id'],
//                        'text'    => 'Ранее была выбрана команда Главное меню',
//                    ]);
//                }
//            } else {
//                \Telegram::sendMessage([
//                    'chat_id' => $telegram['message']['chat']['id'],
//                    'text'    => 'Вы ввели не сущетсвующую команду',
//                ]);
//            }

    }


    public function checkCommand()
    {
        $telegram = $this->telegram_webhook;
        if (isset($telegram['callback_query'])) {
            if ($this->getLastCommand() == null) {
                \Telegram::sendMessage([
                    'chat_id' => $telegram['callback_query']['chat']['id'],
                    'text'    => 'Ошибка - поле last command empty',
                ]);
            } else {
                if ($telegram['callback_query']['data'] == 'SetData') {
                    $this->saveLastCommand();
                } elseif ($telegram['callback_query']['data'] == '/start') {
                    $this->saveLastCommand();
                } elseif ($telegram['callback_query']['data'] == 'Указать') {
                    $this->saveLastCommand();
                } elseif ($telegram['callback_query']['data'] == 'ResetData') {
                    $this->saveLastCommand();
                }
            }
        }

    }

    public function setDataCommand()
    {
        $telegram = $this->telegram_webhook;
        //    file_put_contents('webHook_first.log', '------'.$telegram."------\n\n", FILE_APPEND);
        if (isset($telegram['callback_query'])) {
            $user    = TelegramUser::find($telegram['callback_query']['from']['id']);
            $chat_id = $telegram['callback_query']['message']['chat']['id'];
        } else {
            $user    = TelegramUser::find($telegram['message']['from']['id']);
            $chat_id = $telegram['message']['chat']['id'];
        }

        if ($user->json == null) {
            $arr        = [
                'name'  => 'null',
                'phone' => 'null'

            ];
            $user->json = json_encode($arr, true);
            $user->save();
        }
        $array = json_decode($user->json, true);
        file_put_contents('webHook_first.log', 'setDatacomand------'.var_export($array, true)."------\n\n",
            FILE_APPEND);

        $data = $this->getLastCommand();

        switch ($data) {
            case "Указать":

                if ($array['name'] != 'null') {
                    if ($array['phone'] != 'null') {
                        $param    = [
                            'inline_keyboard' => [
                                [
                                    ['text' => "Стереть данные", 'callback_data' => "ResetData"],
                                    ['text' => "Главное меню", 'callback_data' => "/start"]
                                ]
                            ],
                        ];
                        $response = \Telegram::sendMessage([
                            'chat_id'      => $chat_id,
                            'text'         => 'Всё отлично, больше нет необходимых данных '.'Ваше указанное имя: '
                                              .$array['name'].' И указанный номер телефона : '.$array['phone']
                                              .' При необходимости вы можете ввести данные повторно. ',
                            'reply_markup' => $this->inlineKeyBoard($param)
                        ]);
                    } else {


                        if (isset($telegram['message']['text'])
                            && $user->update_id != Telegram::getWebhookUpdates()['update_id']
                        ) {

                            $array['phone'] = $telegram['message']['text'];
                            $user->json     = json_encode($array, true);
                            $user->save();
                            $this->setDataCommand();
                        }
                        if ($array['phone'] == 'null') {
                            $response = \Telegram::sendMessage([
                                'chat_id' => $chat_id,
                                'text'    => 'Пожалуйста, укажите ваш номер телефона'
                            ]);
                        }
                    }
                } else {
                    file_put_contents('webHook_first.log',
                        'setDatacomand------'.Telegram::getWebhookUpdates()['update_id']."------\n\n", FILE_APPEND);
                    if (isset($telegram['message']['text'])) {

                        $array['name']   = $telegram['message']['text'];
                        $user->json      = json_encode($array, true);
                        $user->update_id = Telegram::getWebhookUpdates()['update_id'];
                        $user->save();
                        $this->setDataCommand();
                    }
                    if ($array['name'] == 'null') {
                        $response = \Telegram::sendMessage([
                            'chat_id' => $chat_id,
                            'text'    => 'Пожалуйста, укажите ваше имя'
                        ]);
                    }

                }
                break;
            case "ResetData":

                $arr        = [
                    'name'  => 'null',
                    'phone' => 'null'

                ];
                $user->json = json_encode($arr, true);
                $user->save();
                $response = \Telegram::sendMessage([
                    'chat_id' => $chat_id,
                    'text'    => 'Данные стёрты'

                ]);
                $param = [
                    'inline_keyboard' => [
                        [
                            ['text' => "Указать данные", 'callback_data' => "Указать"],
                            ['text' => "Главное меню", 'callback_data' => "/start"]
                        ]
                    ],
                ];

                $response = \Telegram::sendMessage([
                    'chat_id'      => $chat_id,
                    'text'         => 'Пожалуйста укажите ваше имя и номер телефона',
                    'reply_markup' => $this->inlineKeyBoard($param)
                ]);

                break;
            default:
                $param = [
                    'inline_keyboard' => [
                        [
                            ['text' => "Указать данные", 'callback_data' => "Указать"],
                            ['text' => "Главное меню", 'callback_data' => "/start"]
                        ]
                    ],
                ];

                $response = \Telegram::sendMessage([
                    'chat_id'      => $chat_id,
                    'text'         => 'Пожалуйста укажите ваше имя и номер телефона',
                    'reply_markup' => $this->inlineKeyBoard($param)
                ]);
        }

        //  file_put_contents('webHook_first.log', '------'.$name."------\n\n", FILE_APPEND);

        // $array = json_decode($user->json, true);

    }

    public function test()
    {
        $keyboard = [
            'inline_keyboard' => [

resources/views/backend/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    {{--<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>--}}

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-5">
                        <li><a href="{{ route('admin.index') }}">Панель состояния</a> </li>
                        <li> |||||| </li>
                        <li><a href="{{ route('admin.setting.index') }}">Настройки</a> </li>
                        <li> |||||| </li>
                        <li><a href="{{ route('admin.setting.debug') }}">Отладка</a> </li>
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>

</body>

</html>